### ISSUE TITLE
New surface limitation

### ISSUE THREAD

**Issue by jovanlanik** [Cu3PO42/gtk-session-lock#5]
Hi,
I'm currently porting [gtklock](/jovanlanik/gtklock) to use gtk-session-lock.

I have a question about `gtk_session_lock_lock_new_surface`.
The comment for this function specifies:
> You must only ever call this method once for a given lock and monitor.

Is this a limitation of gtk-session-lock or the ext-session-lock-v1 protocol?
It would be useful to create a new lock surface for a monitor after destroying the old one.

**Comment by Cu3PO42** [comment]
Hi,

good to hear gtklock is being updated! I did want to use it myself a good while ago and was sad to see I couldn't at the time. (I'd love a small shoutout whenever you announce the update.)

I admit the docs aren't quite as clear as they could be here. gtk-session-lock adds no limitations on top of the limitations ext-session-lock-v1 has inherently. Or at least not intentionally. The more correct statement is:

At any given time, you can only have one output surface per lock and monitor.

You *should* be able to destroy a GTK window for a monitor and then create a new one for that monitor. Beware that this will probably cause a flash of solid color on said monitor. I would generally not recommend doing this. If you're doing this due to woes with input focus, I'd rather recommend working with upstream rather than hacking around them.

**Comment by jovanlanik** [comment]
Thank you for the answer!

I think I'll give up on the destroying windows approach, maybe user configured monitor priority is a better solution.

Of course once I release gtklock 3.0.0, you will be mentioned in the release notes and the reddit posts. I thank you here as well for the great work on this library.
